import {
  ArchiveBox,
  ArchiveBoxFilled,
  ArrowClockwise,
  Bone,
  BoneFilled,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Cat,
  CatFilled,
  Check,
  CheckCircle,
  CheckCircleFilled,
  ClockCounterClockwise,
  CookingPot,
  CookingPotFilled,
  Dog,
  DogFilled,
  DotsThreeCircle,
  DotsThreeVertical,
  FolderOpen,
  Gear,
  GearFilled,
  Heart,
  HeartBreak,
  HeartBreakFilled,
  HeartFilled,
  Info,
  InfoFilled,
  MapPin,
  MapPinFilled,
  MapPinLine,
  MapPinLineFilled,
  MapTrifold,
  MapTrifoldFilled,
  PencilSimpleLine,
  PlusFeeder,
  Question,
  QuestionFilled,
  SignOut,
  Signpost,
  SignpostFilled,
  ToiletPaper,
  TrashSimple,
  User,
  Users,
  Warning,
  WarningCircle,
  WarningCircleFilled,
  WarningFilled,
  X,
} from '@assets';

export const iconMapper = {
  archiveBox: ArchiveBox,
  archiveBoxFilled: ArchiveBoxFilled,
  arrowClockwise: ArrowClockwise,
  bone: Bone,
  boneFilled: BoneFilled,
  caretDown: CaretDown,
  caretLeft: CaretLeft,
  caretRight: CaretRight,
  caretUp: CaretUp,
  cat: Cat,
  catFilled: CatFilled,
  check: Check,
  checkCircle: CheckCircle,
  checkCircleFilled: CheckCircleFilled,
  clockCounterClockwise: ClockCounterClockwise,
  cookingPot: CookingPot,
  cookingPotFilled: CookingPotFilled,
  dog: Dog,
  dogFilled: DogFilled,
  dotsThreeCircle: DotsThreeCircle,
  dotsThreeVertical: DotsThreeVertical,
  folderOpen: FolderOpen,
  gear: Gear,
  gearFilled: GearFilled,
  heart: Heart,
  heartBreak: HeartBreak,
  heartBreakFilled: HeartBreakFilled,
  heartFilled: HeartFilled,
  info: Info,
  infoFilled: InfoFilled,
  mapPin: MapPin,
  mapPinFilled: MapPinFilled,
  mapPinLine: MapPinLine,
  mapPinLineFilled: MapPinLineFilled,
  mapTrifold: MapTrifold,
  mapTrifoldFilled: MapTrifoldFilled,
  pencilSimpleLine: PencilSimpleLine,
  plusFeeder: PlusFeeder,
  question: Question,
  questionFilled: QuestionFilled,
  signOut: SignOut,
  signpost: Signpost,
  signpostFilled: SignpostFilled,
  toiletPaper: ToiletPaper,
  trashSimple: TrashSimple,
  user: User,
  users: Users,
  warning: Warning,
  warningCircle: WarningCircle,
  warningCircleFilled: WarningCircleFilled,
  warningFilled: WarningFilled,
  x: X,
};
