const TAB_BAR_BORDER_RADIUS = 40;
const TAB_BAR_BOTTOM_SPACING = 15;
const TAB_BAR_LEFT_SPACING = 80;
const TAB_BAR_RIGHT_SPACING = 80;
const TAB_BAR_ITEM_BORDER_RADIUS = 40;
const TAB_BAR_ITEM_MARGIN = 4;

export {
  TAB_BAR_BORDER_RADIUS,
  TAB_BAR_BOTTOM_SPACING,
  TAB_BAR_LEFT_SPACING,
  TAB_BAR_RIGHT_SPACING,
  TAB_BAR_ITEM_BORDER_RADIUS,
  TAB_BAR_ITEM_MARGIN,
};
